apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: house-prediction-train # Executable ID (max length 64 lowercase-hyphen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `first-pipeline-1234`
  annotations:
    scenarios.ai.sap.com/description: "house-prediction-train"
    scenarios.ai.sap.com/name: "HOUSEPRICE_PREDICTION"
    executables.ai.sap.com/description: "trying to start a fresh flow on how to predict the hosue prediction"
    executables.ai.sap.com/name: "HOUSEPRICE_PREDICTION Pipeline"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "3.0"
spec:
  imagePullSecrets:
    -name:roshan1727
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: hp_start
        template: house_price

  - name: house_price
    container:
      image: docker.io/python:latest
      command:
        - python3
        - '-c'
      args:
       - |
        print("Hello my name rakesh started to work on house price prediction")
