apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: house-prediction-train
  annotations:
    scenarios.ai.sap.com/description: "Training pipeline for house price prediction model"
    scenarios.ai.sap.com/name: "House Price Prediction"
    executables.ai.sap.com/description: "Pipeline for training a machine learning model to predict house prices"
    executables.ai.sap.com/name: "House Price Prediction Pipeline"
    artifacts.ai.sap.com/housedataset.kind: "dataset"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "3.0"
spec:
  imagePullSecrets:
    - name: roshan1727 # Replace with your Docker registry secret name
  entrypoint: mypipeline
  arguments:
    parameters:
      -name: DT_MAX_DEPTH
  templates:
    - name: mypipeline
      steps:
        - - name: start-house-prediction
            template: house_price

    - name: house_price
      metadata:
        labels:
          ai.sap.com/resourcePlan: starter
      input:
        artifacts:
          -name: homedataset
          path: /app/data/
      container:
        image: docker.io/roshan1727/house-price:03
        command: ["/bin/sh", "-c"]
        env:
          - name: DT_MAX_DEPTH
            value: "{{workflow.parameters.DT_MAX_DEPTH}}"
        args:
          - "python /app/src/main.py"
